apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
#  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
spec:
  accessModes:
    - ReadWriteOnce
#volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
