apiVersion: v1
kind: PersistentVolume
metadata:
  name:  drupal-mysql-pv
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: manual
  capacity:
   storage: "1Gi"
  hostPath:
   path: /tmp/drupal-mysql-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  drupal-pv
spec:
  storageClassName: manual 
  accessModes: [ "ReadWriteOnce" ]
  capacity:
   storage: "1Gi"
  hostPath:
   path: /tmp/drupal-pv
