apiVersion: v1
kind: PersistentVolume
metadata:
  name:  drupal-mysql-pv
spec:
  accessModes: [ "ReadWriteOnce" ]
#  storageClassName: manual
  capacity:
   storage: "5Gi"
  hostPath:
   path: /drupal-mysql-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  drupal-pv
spec:
#  storageClassName: manual 
  accessModes: [ "ReadWriteOnce" ]
  capacity:
   storage: "5Gi"
  hostPath:
   path: /drupal-data
